# <center>Sprawozdanie z laboratorium numer 1<center>


***<center>Przebieg ćwiczenia</center>***

***Importowanie niezbędnych bibliotek***

In [11]:
import main
import numpy as np
import math

***Zadanie 1***     
Zaimplementowanie funkcji $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$

In [12]:
main.cylinder_area(2.1,1.2)

43.54247417875453

***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą

In [13]:
print(np.arange(0, 7, 0.5))
print(np.linspace(4,9,10))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]
[4.         4.55555556 5.11111111 5.66666667 6.22222222 6.77777778
 7.33333333 7.88888889 8.44444444 9.        ]


***Zadanie 3.***    
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego]

In [14]:
main.fib(15)

[array([  1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144, 233,
        377, 610])]

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz

In [15]:
print(main.matrix_calculations(4))

(array([[ 0.09375,  0.53125, -0.15625],
       [ 0.125  ,  0.375  ,  0.125  ],
       [-0.125  ,  0.625  , -0.125  ]]), array([[ 4.,  0., -4.],
       [ 1.,  1.,  4.],
       [-4.,  1.,  1.]]), -32.0)


***Zadanie 5.***  
Stwórz w noataniku macierz i wykonaj kilka operacji

In [16]:
M = np.array([[3,1,-2,4],[0,1,1,5],[-2,1,1,6],[4,3,0,1]])
print(M[0,0])
print(M[2,2])
print(M[2,1])
w1 = M[:,2]
w2 = M[1,:]
print(w1)
print(w2)

3
1
1
[-2  1  1  0]
[0 1 1 5]


***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$ według wymagań

In [17]:
print(main.custom_matrix(4,5))

[[0. 1. 2. 3. 4.]
 [1. 1. 2. 3. 4.]
 [2. 2. 2. 3. 4.]
 [3. 3. 3. 3. 4.]]


***Zadanie 7.***    
Zapoznać się z metodami mnożenia biblioteki numpy oraz wykonać kilka operacji

In [18]:
v1 =np.array([[1],[3],[13]])
v2 =np.array([[8],[5],[-2]])
print(4*v1)
print(-1*v2 + [[2],[2],[2]])
print(np.matmul(v1,np.transpose(v2)))
print(np.multiply(v1,v2))

[[ 4]
 [12]
 [52]]
[[-6]
 [-3]
 [ 4]]
[[  8   5  -2]
 [ 24  15  -6]
 [104  65 -26]]
[[  8]
 [ 15]
 [-26]]


***Zadanie 8***     
Wykonać operacje na macierzy i wypisać ich wynik

In [19]:
M = np.array([[1,-7,3],[-12,3,4],[5,13,-3]])
print(3*M)
print(3*M + np.ones(3))
print(np.transpose(M))
print(np.matmul(M,v1))
print(np.matmul(np.transpose(v2),M))

[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
[[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
[[19]
 [49]
 [ 5]]
[[-62 -67  50]]


***<center> Wnioski </center>***  

Ćwiczenie miało za zadanie zapoznać studentów z podstawowymi funkcjami pythona, biblioteki numpy oraz operacjami na macierzach. Ćwiczenie to jest bardzo przystępne i mertoryczne. W zadaniach problem stwarza fakt że nie jest sprecyzowane czy wartoś NaN w kodzie ma być zaimplementowana jako $math.none$ czy $None$, jednak analizując testy można to wywnioskować
